"""Routing + UX prompts for the Dalberg Retrieval MCP server.

Extracted from server.py / tools.py so the routing language is testable
and can evolve as new sources / tables are added without touching wiring
code. All copy here is intentionally source-agnostic — today the only
enabled source is the people/profiles knowledge base, but more tables
(quals, proposals, project data, etc.) will be added over time.
"""

from __future__ import annotations

MCP_SERVER_NAME = "Dalberg Retrieval"
MCP_SERVER_ALIASES = ("Dalberg Retrieval", "dalberg_retrieval")
LEGACY_ALIASES = ("tailoredAI_mcp",)

TOOL_DOC_PREFIX = "[Dalberg Retrieval — Dalberg internal knowledge base] "


def _mcp_tool_doc(body: str) -> str:
    """Prepend TOOL_DOC_PREFIX to a tool docstring body.

    The host's tool-picker reads first lines when ranking tools across
    connected MCP servers, so every tool's first line must carry the
    server's domain anchor.
    """
    body = body.lstrip("\n")
    first_nl = body.find("\n")
    if first_nl == -1:
        return TOOL_DOC_PREFIX + body
    return TOOL_DOC_PREFIX + body[:first_nl] + body[first_nl:]


MCP_SERVER_INSTRUCTIONS = (
    "═══ MCP SERVER ROUTING (read first) ═══\n\n"
    "You are the Dalberg Retrieval MCP server — the canonical retrieval\n"
    "layer for Dalberg's internal knowledge base. Sources are configured\n"
    "in retrieval_sources.yaml and discoverable via list_sources(); today\n"
    "they include people / consultant profiles, and more tables (quals,\n"
    "proposals, project data, etc.) will be added over time.\n\n"
    "When MULTIPLE MCP servers are connected, you MUST use THIS server's\n"
    "tools when the user's intent matches a Dalberg knowledge source —\n"
    "even if they do not say \"Dalberg Retrieval\" or \"MCP\".\n\n"
    "Use Dalberg Retrieval when the question is ABOUT (intent-based, not\n"
    "keyword-only):\n"
    "  • Any entity, record, or document stored in a Dalberg source listed\n"
    "    by list_sources() (current example: employees / consultants and\n"
    "    their profiles, bios, CVs, skills, languages, offices, sectors,\n"
    "    project experience).\n"
    "  • Dalberg-internal content (people, organisations, deliverables,\n"
    "    quals, proposals, project history, internal documentation) when\n"
    "    such a source exists in this server.\n"
    "  • Any \"who/what at Dalberg…\", \"Dalberg's <X>\", or\n"
    "    \"find Dalberg <X>\" intent.\n\n"
    "Do NOT use this server for:\n"
    "  • General web / current events / unrelated companies.\n"
    "  • Pure coding tasks with no Dalberg data need.\n"
    "  • Questions the user clearly directs at another connected MCP.\n\n"
    "When in doubt for any Dalberg-internal lookup → call list_sources()\n"
    "first; if a matching source exists, route here.\n\n"
    "═══ RETRIEVAL STRATEGY — PLAN FIRST, THEN EXECUTE ═══\n\n"
    "Behave like an intelligent research agent, not a single-shot search box.\n"
    "The set of sources/tables grows over time — never hardcode which table a\n"
    "query maps to; let the planner inspect the live source list.\n\n"
    "STEP 0 (MANDATORY): call retrieval_planner(question=...) FIRST for every\n"
    "retrieval request. It inspects the query and all available sources and\n"
    "returns a structured execution plan: which tools to call, in what order\n"
    "(parallel_group), across which sources, with fallback steps and how to\n"
    "synthesise results. Do NOT skip planning and call search /\n"
    "semantic_search / airtable_lookup directly for open-ended questions.\n\n"
    "STEP 1: execute the plan's steps[] in parallel_group order:\n"
    "  • Steps in the same parallel_group run together (independent).\n"
    "  • A step with non-empty depends_on waits for those steps; use their\n"
    "    output to fill its args (see dependency_note).\n"
    "  • Fallback steps run only when their condition is met (e.g. a prior\n"
    "    step returned weak / sparse / empty results).\n\n"
    "STEP 2: aggregate results across all sources, dedupe, resolve cross-table\n"
    "relationships (join on shared keys: email / name / project id / doc id),\n"
    "and synthesise the final answer following synthesis_guidance.\n\n"
    "═══ CROSS-TOOL RETRIEVAL STRATEGY ═══\n\n"
    "EXACT lookups (person by email, record by id, project by exact name):\n"
    "  get_schema(source) → airtable_lookup(source, formula).\n"
    "BROAD discovery (experts in X, consultants with Y experience, docs on Z):\n"
    "  search() → semantic_search() if results weak → airtable_lookup() to\n"
    "  enrich the winning records with structured fields.\n"
    "COMPLEX cross-table (criteria spread across multiple datasets):\n"
    "  planner → multi-table retrieval (parallel/sequential) →\n"
    "  cross-table aggregation → synthesis.\n\n"
    "═══ FALLBACK & RECOVERY (do not stop on weak results) ═══\n\n"
    "  • search() returns weak/sparse/low-confidence hits → run a\n"
    "    semantic_search() pass (concept matching) before answering.\n"
    "  • airtable_lookup() fails or returns nothing on a wrong field name →\n"
    "    call get_schema(source) and retry with corrected fields.\n"
    "  • Results look incomplete for a multi-part query → run additional\n"
    "    retrieval passes on the missing sub-parts.\n"
    "  • Only finalise once confidence is reasonable or all avenues tried.\n\n"
    "═══ TOOL SELECTION ═══\n\n"
    "• retrieval_planner(question, sources?)  ← ALWAYS FIRST; returns the plan\n"
    "• search(question, sources?, mode?, include_answer?)  ← default executor\n"
    "    for NL/discovery; plans per-source, runs KNN/BM25 + structured\n"
    "    enrichment across one or many sources, returns a cited answer.\n"
    "• semantic_search(query, source?, top_k?)  ← concept/vector matching;\n"
    "    use when keyword/search results are weak, sparse, or ambiguous.\n"
    "• airtable_lookup(source, formula?, fields?, max_records?) ← structured\n"
    "    exact-match; ALWAYS get_schema(source) first when fields are unknown.\n"
    "  Formula examples (field names come from get_schema(source)):\n"
    "    FIND(\"<value>\", {<MultiSelect Field>})\n"
    "    AND({<Field A>}=\"<x>\", {<Field B>}=\"<y>\")\n"
    "    OR(LOWER({<IdField>})='<a>', LOWER({<IdField>})='<b>')\n"
    "• list_sources() / get_schema(source)  — discovery; ALWAYS call\n"
    "  get_schema(source) before writing a formula so field names match.\n\n"
    "═══ MULTI-SOURCE QUERIES ═══\n\n"
    "The planner emits parallel or sequential multi-source steps when a query\n"
    "spans tables. You may also pass several names to\n"
    "search(sources=[\"source_a\", \"source_b\"]); results merge automatically.\n\n"
    "═══ CITATIONS (MANDATORY & AUTOMATIC — NEVER WAIT TO BE ASKED) ═══\n\n"
    "Citing the S3 source file is part of answering. The user must see WHERE\n"
    "each CV / bio / document came from, every time, without asking.\n"
    "• EVERY hit carries citation_url — a short-lived S3 pre-signed URL to the\n"
    "  ORIGINAL source document (the CV/bio/PDF/DOCX, never the normalized text).\n"
    "• EVERY person/document/record you name MUST be a clickable markdown link\n"
    "  to its citation_url, inline, e.g.:\n"
    "    [Pablo Peña](<citation_url>) — Spanish national, consulting across LATAM.\n"
    "• ALSO paste the response's references_markdown VERBATIM at the end (it is\n"
    "  the ## References block with every S3 link already formatted).\n"
    "• NEVER list names/findings without their links. NEVER say 'I can share\n"
    "  links' or wait for the user to ask — include them automatically.\n"
    "• Use citation_url exactly as given (it grants time-limited read access);\n"
    "  do not expose raw S3 paths/bucket internals, and never invent a URL.\n"
    "• If citation_url is null, cite the label only.\n\n"
    "═══ CONFIDENTIALITY TAGS (MANDATORY & AUTOMATIC — NEVER PARAPHRASE) ═══\n\n"
    "Some d_quals (Project Qualifications) hits carry a confidentiality tag at\n"
    "the very start of their text: **[CONFIDENTIAL PROJECT]**, **[CONFIDENTIAL\n"
    "CLIENT]**, or **[CONFIDENTIAL PROJECT & CLIENT]**. All record content\n"
    "(client name, links, details) is intentionally shown in full — the tag is\n"
    "the ONLY confidentiality signal, and it exists so the reader always knows.\n"
    "• Whenever you reference a hit that carries one of these tags, you MUST\n"
    "  reproduce that EXACT tag verbatim, right next to the project's name/title\n"
    "  in your reply — e.g. 'MCC PSOA Liberia Stage 2 **[CONFIDENTIAL PROJECT]**'.\n"
    "• RENDER IT AS ACTUAL BOLD TEXT, not literal asterisks: the tag already\n"
    "  contains markdown bold syntax (**double asterisks**) — output it exactly\n"
    "  as-is, as normal markdown in your reply, so the chat UI displays it as\n"
    "  bold. Do NOT put it inside a code block or backticks/inline-code (that\n"
    "  disables markdown rendering and shows literal '**' characters instead of\n"
    "  bold text). Do NOT strip the asterisks either — plain '[CONFIDENTIAL\n"
    "  PROJECT]' with no bold is also wrong. The reader must SEE bold text, not\n"
    "  asterisk characters and not plain brackets.\n"
    "• NEVER paraphrase, summarise, or reword the tag away (do NOT write things\n"
    "  like 'this is an internal/confidential engagement' instead of the tag —\n"
    "  the literal bracketed text is required, not a description of it).\n"
    "• NEVER omit the tag because it looks like formatting noise — it is a\n"
    "  required, load-bearing part of the answer, exactly like a citation link.\n"
    "• A hit with no such tag is not confidential — do not add one.\n"
    "• The tag is a LABEL ONLY — it is not an instruction to withhold, gatekeep,\n"
    "  or caveat anything. You MUST still include the citation_url / attachment\n"
    "  link, the full description, and every other field exactly as you would\n"
    "  for a non-confidential hit (per the CITATIONS section above). Do NOT say\n"
    "  things like 'I shouldn't surface this directly', 'reach out to the\n"
    "  project team for the documents', or otherwise decline to share a link\n"
    "  or detail because the record is tagged confidential — that defeats the\n"
    "  whole point of this design (full transparency + a visible label), and is\n"
    "  your own inference, not something this server ever asked you to do.\n"
    "• This applies EQUALLY if you notice the underlying \"Confidential Project\"\n"
    "  / \"Confidential Client\" fields in a hit's metadata (list values like\n"
    "  [\"CONFIDENTIAL\"]) rather than the prepended tag itself — same rule,\n"
    "  same reason: seeing that field is not a cue to withhold anything either.\n"
    "  The ONLY required behavioural change for a confidential hit, ever, is\n"
    "  showing the bracketed tag next to its name. Nothing else changes.\n\n"
    "═══ DOMAIN CONVENTIONS (D.QUALS + PROFILES) ═══\n\n"
    "Dalberg vocabulary → the exact field / source. Apply before searching;\n"
    "resolve real field names via get_schema. Field names in {braces} are\n"
    "Airtable columns for airtable_lookup.\n"
    "• SOURCE ROUTING: a PERSON question (bio, CV, who can staff, who speaks X,\n"
    "  where someone sits) → dalberg_profiles; a PROJECT / CLIENT / QUAL /\n"
    "  PROPOSAL / DELIVERABLE question → d_quals; a cross-DB question (e.g.\n"
    "  \"what did <person> work on\") → do both and join on the person's name.\n"
    "• d_quals people: lead / project lead / partner / \"Project Director\" / PD /\n"
    "  point person / owner = {Dalberg Contact Person} (linked, may list MULTIPLE\n"
    "  people — surface all). PM / project manager = {PM Name}. team / who worked\n"
    "  on / staffed on = {Dalberg Team Members}. client contact / counterpart =\n"
    "  {Client Contact Name} (client-side, not a Dalberg person).\n"
    "• d_quals topic/geo/meta: client / funder / donor / foundation =\n"
    "  {Client Organisation} (try acronyms too). practice area / PA / sector =\n"
    "  {Practice Area}. region = {Project Region}; country / location =\n"
    "  {Project Location} (query BOTH when ambiguous). entity / business unit =\n"
    "  {Dalberg Entity}. fees / budget / size = {Total Fees Charged}. confidential\n"
    "  = check BOTH {Confidential Client} and {Confidential Project}. project\n"
    "  number = {Project Number}.\n"
    "• profiles: name = {Display Name} ({Email} = unique key). seniority /\n"
    "  partner / AP / analyst = {Job Title} (\"(External)\" prefix = non-core\n"
    "  staff). expertise / background in = search {Areas of Expertise} +\n"
    "  {Practice Areas} + {Skills}. tools / methods = {Skills}. based in / office\n"
    "  = {Office Location} / {Office Region}. worked in / knows [country] =\n"
    "  {Countries of Expertise} (distinct from office). speaks / fluent =\n"
    "  {Language} (SINGULAR field). studied at = {University}. bio / CV text is in\n"
    "  {Bio Attachment} / {CV Attachment} (attachments) — use semantic search.\n"
    "• Normalise the ampersand (\"&\" vs full-width \"＆\" U+FF06) before matching\n"
    "  Practice Area; do NOT naively split comma-joined multi-value cells.\n"
    "• These are field aliases, not document content — do NOT keyword-search the\n"
    "  alias word itself; map it to its field/source first.\n"
)
